# Generated by Django 3.1.2 on 2020-11-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年齢'),
        ),
    ]
