# Generated by Django 3.1.2 on 2020-11-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201103_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experiense',
            field=models.IntegerField(default=0, verbose_name='経験年数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='居住地'),
        ),
    ]
