# Generated by Django 3.1.2 on 2020-10-07 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名前')),
                ('age', models.IntegerField(max_length=11, verbose_name='年齢')),
                ('address', models.CharField(max_length=161, verbose_name='住所')),
                ('experiense', models.IntegerField(max_length=11, verbose_name='経験年数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
            ],
        ),
    ]
