# Generated by Django 3.1.2 on 2020-10-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
