# Generated by Django 3.1.2 on 2020-10-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_comment_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='last_name',
            new_name='name',
        ),
    ]
