# Generated by Django 3.1.2 on 2020-10-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20201023_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posted_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
    ]
