# Generated by Django 3.1.2 on 2020-11-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(),
        ),
    ]
