# Generated by Django 3.1.2 on 2020-11-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20201103_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='メッセージ'),
        ),
    ]
