# Generated by Django 3.1.2 on 2020-11-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20201103_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name=''),
        ),
    ]
